name: Release

on:
  push:
    tags:
      - '*'
  
  workflow_dispatch:

jobs:
  build_container_image_from_release:
    strategy:
      matrix:
        java-version: [11, 17]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
              
      - name: Load environment variables from .env files 
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: variables.env
        
      - name: Test imported environment variables ARCH
        shell: bash
        run: |
          echo "PROJECT_VERSION: $PROJECT_VERSION"
          echo "DOCKER_ARCH: $DOCKER_ARCH"
          echo "DOCKER_CONTAINER: $DOCKER_CONTAINER"
          echo "BASE_MULTIARCH_VERSION: $BASE_MULTIARCH_VERSION"
          echo "GRAALVM_VERSION: $GRAALVM_VERSION"
          echo "DOCKER_REPO: $DOCKER_REPO"

      - name: Get the version
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF##refs/tags/v}"

      - name: Build the Docker image - Java ${{ matrix.java-version }}
        run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            docker build --build-arg BASE_MULTIARCH_VERSION=${BASE_MULTIARCH_VERSION} --build-arg DOCKER_ARCH=${DOCKER_ARCH} --build-arg GRAALVM_VERSION=${GRAALVM_VERSION} --build-arg JAVA_VERSION=${{ matrix.java-version }} -t "${DOCKER_CONTAINER}:${{ steps.get_version.outputs.VERSION }}-java${{ matrix.java-version }}" --platform ${DOCKER_ARCH} --pull -f Dockerfile.multiarch-aarch64 .
            docker tag $DOCKER_CONTAINER:${{ steps.get_version.outputs.VERSION }}-java${{ matrix.java-version }} $DOCKER_CONTAINER:latest-java${{ matrix.java-version }}
      - name: Push To Quay - Java ${{ matrix.java-version }}
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.DOCKER_CONTAINER }}
          tags: ${{ steps.get_version.outputs.VERSION }}-java${{ matrix.java-version }} latest-java${{ matrix.java-version }}
          registry: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.QUAY_ALL_USERNAME }}
          password: ${{ secrets.QUAY_ALL_PASSWORD }}
