name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_ARCH: aarch64
  DOCKER_CONTAINER: quarkus-ubi-multiarch-builder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            docker build --build-arg GRAALVM_VERSION=21.2.0 -t "${DOCKER_CONTAINER}:${{ github.sha }}" --platform ${DOCKER_ARCH} --pull .
